name: Test Pytest per Orario

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installa dipendenze
        run: |
          pip install pytest
          pip install -r requirements.txt || true

      - name: Esegui i test
        run: pytest